# App Info
ios_app_id                                : 1476436116                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : NapBot
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Machine Learning powered sleep tracker for your Apple Watch and iPhone

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Majid Jabrayilov
your_link                                 : https://mecid.github.io
your_city                                 : Baku
email_address                             : cmecid@gmail.com
facebook_username                         : majid.jabrayilov                                          
instagram_username                        : mecid8
twitter_username                          : mecid
github_username                           : mecid
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Sleep History
    description                           : Gain insight into your full sleep history in beautifully designed overviews.
    fontawesome_icon_name                 : calendar-alt
    
  - title                                 : Sleep Tracking
    description                           : NapBot uses machine learning to automatically track your sleep.
    fontawesome_icon_name                 : bed

  - title                                 : Detailed Sleep Analysis
    description                           : NapBot presents detailed sleep phases analysis by calculating deep and light phases.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Environmental Sound Exposure
    description                           : NapBot analyze your Environmental Exposure to understand how it affects your sleep quality.
    fontawesome_icon_name                 : microphone-alt

  - title                                 : Sleep Heart Rate
    description                           : NapBot presents sleep Heart Rate summary chart based on your HR zones.
    fontawesome_icon_name                 : heartbeat

  - title                                 : Sleep Trends
    description                           : Track your sleep trends to understand how new habits influence your sleep.
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000"

link_color                                : "#af52de"

app_title_color                           : "#fff"
app_price_color                           : "#fff"
app_description_color                     : "#fff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#af52de"
feature_icons_background_color            : "#222"

social_icons_foreground_color             : "#af52de"
social_icons_background_color             : "#222"

footer_text_color                         : "#fff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
