# App Info
ios_app_id                                : 1476436116                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : NapBot
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Machine Learning powered automatic sleep tracker for your Apple Watch and iPhone

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Majid Jabrayilov
your_link                                 : https://mecid.github.io
your_city                                 : Baku
email_address                             : cmecid@gmail.com
facebook_username                         : majid.jabrayilov                                          
instagram_username                        : mecid8
twitter_username                          : mecid
github_username                           : mecid
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Monthly Heart Rate
    description                           : CardioBot presents daily Heart Rate average in a beautiful calendar view during the month.
    fontawesome_icon_name                 : calendar-alt
    
  - title                                 : Daily Heart Rate
    description                           : CardioBot presents daily Heart Rate summary chart based on your HR zones.
    fontawesome_icon_name                 : heartbeat

  - title                                 : Heart Rate Variability
    description                           : CardioBot calculates your Heart Rate Variability baseline/trend during the 40 days, and show you daily sample analysis.
    fontawesome_icon_name                 : balance-scale

  - title                                 : Sedentary Heart Rate
    description                           : CardioBot makes Sedentary Heart Rate analysis to understand your cardio health.
    fontawesome_icon_name                 : chair
    
  - title                                 : Sleep and Weekly Sleep
    description                           : By wearing Apple Watch during the sleep you enable Sleep analysis in CardioBot. It presents your sleep quality and calculates weekly sleep goal achievement.
    fontawesome_icon_name                 : bed

  - title                                 : Walking Heart Rate
    description                           : CardioBot makes Walking Heart Rate analysis to calculate and show your overall physical activity state.
    fontawesome_icon_name                 : walking
  
  - title                                 : Workout
    description                           : CardioBot makes your Heart Rate analysis during workout to calculate your workout quality score.
    fontawesome_icon_name                 : running

  - title                                 : Detailed per minute charts
    description                           : You can check detailed per minute heart rate charts with heart rate zone indication.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Recommendation system
    description                           : CardioBot powered by smart recommendation system, which analyze you Heart Rate and give you recommendations on improving every aspect of your heart.
    fontawesome_icon_name                 : comments

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000"

link_color                                : "#1d63ea"

app_title_color                           : "#000"
app_price_color                           : "#000"
app_description_color                     : "#000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
